name: Backport
on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: 'stable'

permissions:
  contents: write
  pull-requests: write

jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    # Only run if:
    #  - triggered by pull request merging, or
    #  - a label starting with `backport ` is added to a merged PR, or
    #  - `/backport` commented on a PR by someone other than "Sei Platform / Code Agent" GitHub App.
    if: >
      (
        github.event_name == 'pull_request_target' &&
        github.event.pull_request.merged
      ) || (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        github.event.comment.user.id != fromJSON(vars.PLATFORM_CODE_AGENT_USER_ID) &&
        startsWith(github.event.comment.body, '/backport')
      )
    steps:
      - name: Generate GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.PLATFORM_CODE_AGENT_APP_ID }}
          private-key: ${{ secrets.PLATFORM_CODE_AGENT_APP_PK }}

      - uses: actions/checkout@v6
      - name: Create backport pull requests
        uses: korthout/backport-action@v4.0.1
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          add_author_as_assignee: 'true'
          copy_assignees: 'true'
          add_labels: 'backport'
          pull_title: |-
            Backport `${target_branch}`: ${pull_title}
          pull_description: |-
            Backport of #${pull_number} to `${target_branch}`.
          experimental: |-
            {
              "conflict_resolution": "draft_commit_conflicts"
            }