name: Backport
on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: 'stable'

permissions:
  contents: write
  pull-requests: write

jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    # Only run if:
    #  - triggered by pull request merging, or
    #  - a label starting with `backport ` is added to a merged PR, or
    if: >
      github.event_name == 'pull_request_target' &&
      github.event.pull_request.merged &&
      (
        github.event.action == 'closed' ||
        (github.event.action == 'labeled' && startsWith(github.event.label.name, 'backport '))
      )
    steps:
      - uses: actions/checkout@v4
      - name: Create backport pull requests
        uses: korthout/backport-action@v4
        with:
          add_author_as_assignee: 'true'
          copy_assignees: 'true'
          add_labels: 'backport'
          pull_title: |-
            [Backport ${target_branch}: ${pull_title}
          pull_description: |-
            Backport of #${pull_number} to `${target_branch}`.
