name: Go

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: 'stable'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          # TODO: Automate fetch from go.mod.
          go-version: '${{ inputs.go-version }}'
      - name: Run repo-specific setup
        uses: ./.github/actions/go-lint-setup
        if: hashFiles('./.github/actions/go-lint-setup') != ''
      - name: Check module tidiness
        run: |
          had_sum=$( [ -f go.sum ] && echo true || echo false )
          go mod tidy
          git diff --exit-code go.mod
          if [ -f go.sum ]; then
            if [ "$had_sum" = true ]; then
              git diff --exit-code go.sum
            else
              echo "error: go.sum was created by 'go mod tidy' but is not checked in"
              exit 1
            fi
          fi
      - name: Vet Go files
        if: always()
        run: go vet ./...
      - name: Check formatting
        if: always()
        run: |
          if out="$(gofmt -s -l .)" && test -n "$out"; then
            echo "Files not gofmt-ed:"
            echo "$out";
            exit 1
          fi
      - name: Check generated files
        if: always()
        run: |
          go generate -x ./...
          git diff --exit-code
